name: Node.js CI

on:
  push:
    branches: 
      - "main"
      - "develop"  # Add develop branch
  pull_request:
    branches: 
      - "main"
      - "develop"  # Add develop branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./teste/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: ./teste  # Adjust path as needed

    - name: Build the project
      run: npm run build --if-present
      working-directory: ./teste  # Adjust path as needed

  test:
    needs: build  # Job depends on build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./teste/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: ./teste  # Adjust path as needed

    - name: Run tests
      run: npm test
      working-directory: ./teste  # Adjust path as needed
