name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./testes/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: ./teste  # Ajuste o caminho conforme necess치rio

    - name: Build the project
      run: npm run build --if-present
      working-directory: ./teste  # Ajuste o caminho conforme necess치rio

  test:
    needs: build  # Faz com que o job de testes dependa do de build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      working-directory: ./teste  # Ajuste o caminho conforme necess치rio

    - name: Run tests
      run: npm test
      working-directory: ./teste  # Ajuste o caminho conforme necess치rio

