name: Node.js CI

on:
  push:
    branches: 
      - "main"
      - "develop"  # Add develop branch
      - "testes/a5"
  pull_request:
    branches: 
      - "main"
      - "develop"  # Add develop branch
      - "testes/a5"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: ./frontend # Adjust path as needed

    - name: Build the project
      run: npm run build --if-present
      working-directory: ./frontend  # Adjust path as needed

  front-end-tests:
    needs: build  # Job depends on build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: ./frontend  # Adjust path as needed

    - name: Run tests
      run: npm test
      working-directory: ./frontend  # Adjust path as needed

  back-end-tests:
    needs: build  # Job depends on build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Indent this line properly

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run tests
        run: pytest
        working-directory: ./backend  # Adjust path as needed