name: Node.js CI

on:
  push:
    branches: [ "gviterbo-pipeline" ]
  pull_request:
    branches: [ "gviterbo-pipeline" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # Veja o cronograma de lançamentos compatíveis em https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      working-directory: ./teste  # Altere para o diretório correto
    
    - name: Build the project
      run: npm run build --if-present
      working-directory: ./teste  # Altere para o diretório correto
    
    - name: Run tests
      run: npm test
      working-directory: ./teste  # Altere para o diretório correto

